version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: campaign_spends
      - name: lead_activities_agg
  - name: public_public
    schema: public_public
    tables:
      - name: traffic_daily_agg
  - name: atomic
    schema: atomic
    tables:
      - name: events
      - name: com_mycarely_lead_stage_change_2